"""add users and ownership schema

Revision ID: 9e18f8d457c8
Revises: e92ed5ccf419
Create Date: 2026-08-09 17:29:14.135271

DESTRUCTIVE. Per master v2's locked decision ("no backward compatibility required — the
DB holds only POC data"), this migration deletes every existing row in `tracks`, `jobs`,
and `sessions` rather than inventing an owner for them, then makes `jobs.user_id` and
`sessions.user_id` NOT NULL. Do not run this against a database holding data you want to
keep.

Also removes the dead `TrackState.FAILED` enum value (v14/v15 audit finding, routed here
because removing a native enum value needs its own type swap + `DROP TYPE`, same as any
other migration touching this table) — no track has ever actually been assigned this
state; the retry engine always routes failures to `waiting` or `lookup_failed` instead.

Known consequence, intentionally left for v17: `sessions.user_id` is NOT NULL with no
application code yet creating `users` rows or populating it, and `jobs.user_id` is NOT
NULL with nothing populating it either. Login (`POST /api/auth/login`) and job creation
(`POST /api/jobs`) will fail against a real running stack, and the existing auth/job test
suites will fail, until v17 wires user creation on login and scopes job creation to the
authenticated user. This is deliberate — v16 is schema only, matching the v02→v03
schema-then-enforcement split — not a regression to fix here.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9e18f8d457c8'
down_revision: Union[str, Sequence[str], None] = 'e92ed5ccf419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.Text(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('last_login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    op.create_table(
        'user_settings',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('retention_days', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('user_id'),
    )

    # No owner exists for any current row and compatibility isn't required (see module
    # docstring) — wipe children before parents rather than backfilling a fake owner.
    op.execute("DELETE FROM tracks")
    op.execute("DELETE FROM jobs")
    op.execute("DELETE FROM sessions")

    op.add_column('jobs', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_jobs_archived_at'), 'jobs', ['archived_at'])
    op.add_column('jobs', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key('fk_jobs_user_id_users', 'jobs', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'])
    # Composite + partial indexes: hand-written, not autogenerated (v02's gotcha —
    # autogenerate does not emit partial indexes). Must match app/models/job.py exactly.
    op.execute("CREATE INDEX ix_jobs_user_id_created_at ON jobs (user_id, created_at DESC)")
    op.execute(
        "CREATE INDEX ix_jobs_user_id_created_at_active ON jobs (user_id, created_at DESC) "
        "WHERE archived_at IS NULL"
    )

    op.drop_column('sessions', 'email')
    op.add_column('sessions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key('fk_sessions_user_id_users', 'sessions', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'])

    # Postgres has no `DROP VALUE` for enums — recreate the type without 'failed' and
    # swap the column over (v02/v10's enum-value gotcha). `tracks` is already empty from
    # the DELETE above, so the USING cast never has to remap a 'failed' row.
    #
    # The existing partial index's WHERE clause embeds a literal already bound to the old
    # type's OID (renaming a type keeps its OID); ALTER COLUMN TYPE can't rewrite that
    # embedded literal to the new type, so `state = 'waiting'` ends up comparing across
    # two distinct enum types with no operator between them. Drop it first, recreate
    # after the swap once the column is the new type.
    op.drop_index("ix_tracks_scheduled_at_waiting", table_name="tracks")
    op.execute("ALTER TYPE track_state RENAME TO track_state_old")
    op.execute(
        "CREATE TYPE track_state AS ENUM "
        "('pending', 'queued', 'downloading', 'completed', 'waiting', 'lookup_failed', "
        "'skipped_duplicate', 'cancelled')"
    )
    op.execute("ALTER TABLE tracks ALTER COLUMN state TYPE track_state USING state::text::track_state")
    op.execute("DROP TYPE track_state_old")
    op.create_index(
        "ix_tracks_scheduled_at_waiting",
        "tracks",
        ["scheduled_at"],
        postgresql_where=sa.text("state = 'waiting'"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_tracks_scheduled_at_waiting", table_name="tracks")
    op.execute("ALTER TYPE track_state RENAME TO track_state_new")
    op.execute(
        "CREATE TYPE track_state AS ENUM "
        "('pending', 'queued', 'downloading', 'completed', 'waiting', 'lookup_failed', "
        "'failed', 'skipped_duplicate', 'cancelled')"
    )
    op.execute("ALTER TABLE tracks ALTER COLUMN state TYPE track_state USING state::text::track_state")
    op.execute("DROP TYPE track_state_new")
    op.create_index(
        "ix_tracks_scheduled_at_waiting",
        "tracks",
        ["scheduled_at"],
        postgresql_where=sa.text("state = 'waiting'"),
    )

    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_constraint('fk_sessions_user_id_users', 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'user_id')
    op.add_column('sessions', sa.Column('email', sa.Text(), nullable=True))
    op.execute("UPDATE sessions SET email = '' WHERE email IS NULL")
    op.alter_column('sessions', 'email', nullable=False)

    op.execute("DROP INDEX IF EXISTS ix_jobs_user_id_created_at_active")
    op.execute("DROP INDEX IF EXISTS ix_jobs_user_id_created_at")
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_constraint('fk_jobs_user_id_users', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'user_id')
    op.drop_index(op.f('ix_jobs_archived_at'), table_name='jobs')
    op.drop_column('jobs', 'archived_at')

    op.drop_table('user_settings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
