"""initial schema

Revision ID: ebc1d43e2c21
Revises: 
Create Date: 2026-07-28 17:59:08.444696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebc1d43e2c21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloaded_tracks',
    sa.Column('spotify_track_id', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('bitrate', sa.Text(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('spotify_track_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('track', 'album', 'playlist', 'artist', 'search', name='job_source_type'), nullable=False),
    sa.Column('state', sa.Enum('expanding', 'expanded', 'failed', name='job_state'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('file', 'manual', name='proxy_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.create_table('worker_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breaker_tripped_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('breaker_trip_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('spotify_track_id', sa.Text(), nullable=False),
    sa.Column('song_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Enum('pending', 'queued', 'downloading', 'completed', 'waiting', 'lookup_failed', 'failed', 'skipped_duplicate', 'cancelled', name='track_state'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_type', sa.Enum('audio_provider', 'lookup', 'other', name='track_error_type'), nullable=True),
    sa.Column('used_proxy_id', sa.UUID(), nullable=True),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['used_proxy_id'], ['proxies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_job_id'), 'tracks', ['job_id'], unique=False)
    op.create_index('ix_tracks_scheduled_at_waiting', 'tracks', ['scheduled_at'], unique=False, postgresql_where=sa.text("state = 'waiting'"))
    op.create_index(op.f('ix_tracks_spotify_track_id'), 'tracks', ['spotify_track_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the single worker_state row the global circuit breaker reads/writes (v06) —
    # dispatch_due_tracks assumes id=1 always exists rather than upserting it.
    op.execute("INSERT INTO worker_state (id, breaker_trip_count, consecutive_failures, paused) VALUES (1, 0, 0, false)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracks_spotify_track_id'), table_name='tracks')
    op.drop_index('ix_tracks_scheduled_at_waiting', table_name='tracks', postgresql_where=sa.text("state = 'waiting'"))
    op.drop_index(op.f('ix_tracks_job_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_table('worker_state')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('proxies')
    op.drop_table('jobs')
    op.drop_table('downloaded_tracks')
    # ### end Alembic commands ###

    # drop_table doesn't drop the native enum types it implicitly created — do it by hand
    # so `downgrade base` actually reverses everything `upgrade head` created.
    op.execute("DROP TYPE track_error_type")
    op.execute("DROP TYPE track_state")
    op.execute("DROP TYPE proxy_source")
    op.execute("DROP TYPE job_state")
    op.execute("DROP TYPE job_source_type")
